#!/usr/bin/env python3
"""Export the WAPR v0 code tables to C and write golden test vectors.

    python3 wapr_export.py            # writes src/wapr_tables.h and test/wapr/golden/wapr_vectors.txt

The C implementation uses these tables so that it is bit exact with the code that was
evaluated in stage 1 (configs/stage1.json, LDPC rate 1/2, PEG seed 1, interleaver seed 7).
"""

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import wapr_bench      # noqa: E402
import wapr_frame      # noqa: E402
import wapr_phy        # noqa: E402

SYSTEM = 'H150_ldpc'      # any M=4, rate 1/2 LDPC system: the bits and symbols are the same


def c_array(name, ctype, vals, per_line=16):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append('\t' + ', '.join(str(int(v)) for v in vals[i:i + per_line]) + ',')
    return 'static const %s %s[%d] = {\n%s\n};\n' % (ctype, name, len(vals), '\n'.join(lines))


def main():
    _, systems = wapr_bench.load_config(os.path.join(HERE, 'configs', 'stage1.json'))
    prof = systems[SYSTEM]['profile']
    phy = wapr_phy.Phy(prof)
    code = phy.code
    k, n, dv = code.k, code.n, code.dv
    info_chk = np.array([list(r) for r in code.info_rows], dtype=np.int64)
    assert info_chk.shape == (k, dv)
    out = []
    out.append('/* Generated by test/wapr/wapr_export.py from test/wapr/configs/stage1.json.  Do not edit. */\n')
    out.append('/* WAPR v0 code: IRA LDPC, K=%d N=%d, information node degree %d (PEG seed %d), */\n'
               % (k, n, dv, prof['fec']['seed']))
    out.append('/* staircase parity.  Interleaver: tx bit i = codeword bit wapr_perm[i]. */\n\n')
    out.append('#define WAPR_K %d\n#define WAPR_N %d\n#define WAPR_DV %d\n\n' % (k, n, dv))
    out.append(c_array('wapr_info_chk', 'unsigned short', info_chk.reshape(-1)))
    out.append('\n')
    out.append(c_array('wapr_perm', 'unsigned short', phy.perm))
    path = os.path.join(HERE, '..', '..', 'src', 'wapr_tables.h')
    with open(path, 'w', newline='\n') as f:
        f.write(''.join(out))
    print('wrote', os.path.normpath(path))

    # Golden vectors: one line per frame
    #   V type ack seq source dest payload_hex info_hex symbols
    # and malformed information blocks that must be rejected
    #   X reason info_hex
    rng = np.random.default_rng(20261011)
    lines = ['# WAPR v0 golden vectors, generated by test/wapr/wapr_export.py.  Do not edit.',
             '# V type ack seq source dest(- = broadcast) payload_hex(- = empty) info_hex symbols(M=4, 6 sync blocks)',
             '# X reason info_hex  (information block that must be rejected)']
    cases = [(1, False, 0, 'N0CALL', '', b'!4237.14N/07120.83W-PHG2360'),
             (1, True, 1023, 'W1AW-15', 'N0CALL-1', b':N0CALL-1 :hello{001'),
             (0, False, 77, 'A', '', b''),
             (0, False, 5, 'ZZ9ZZZ-9', 'K1ABC', bytes(range(32))),
             (2, False, 12, 'K1ABC-9', '', b'>relayed by a gateway')]
    for i in range(4):
        L = int(rng.integers(0, 33))
        cases.append((int(rng.integers(0, 2)), bool(rng.integers(0, 2)), int(rng.integers(0, 1024)),
                      'N%dTST-%d' % (i, i), '', bytes(rng.integers(0, 256, L).astype(np.uint8))))
    def hexbits(b):
        b = np.asarray(b, dtype=np.uint8)
        pad = (-len(b)) % 8
        b = np.concatenate([b, np.zeros(pad, dtype=np.uint8)])
        return bytes(np.packbits(b)).hex()
    for t, ack, seq, src, dst, pl in cases:
        info = wapr_frame.pack(t, src, dst, seq, pl, ack)
        syms = phy.encode_bits(info)
        lines.append('V %d %d %d %s %s %s %s %s' % (t, int(ack), seq, src, dst or '-', pl.hex() or '-',
                                                     hexbits(info), ''.join(str(s) for s in syms)))
    good = wapr_frame.pack(1, 'N0CALL', '', 1, b'test')
    def bad(reason, edit):
        b = good.copy()
        edit(b)
        try:
            wapr_frame.unpack(b)
        except wapr_frame.FrameError:
            lines.append('X %s %s' % (reason, hexbits(b)))
            return
        raise AssertionError('expected rejection: ' + reason)
    bad('version', lambda b: b.__setitem__(1, 1))
    bad('type', lambda b: b.__setitem__(slice(2, 6), [1, 1, 1, 1]))
    bad('reserved_flag', lambda b: b.__setitem__(7, 1))
    bad('length', lambda b: b.__setitem__(slice(8, 14), [1, 0, 0, 0, 0, 1]))
    bad('padding', lambda b: b.__setitem__(96 + 8 * 20, 1))
    bad('broadcast_source', lambda b: b.__setitem__(slice(24, 60), 0))
    bad('address_range', lambda b: b.__setitem__(slice(60, 96), 1))
    gpath = os.path.join(HERE, 'golden', 'wapr_vectors.txt')
    os.makedirs(os.path.dirname(gpath), exist_ok=True)
    with open(gpath, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', os.path.normpath(gpath))


if __name__ == '__main__':
    main()
